//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPNHAP
    {
        /// <summary>
        /// 
        /// </summary>
        public int sophieu { get; set; }
        public string mathuoc { get; set; }
        public string dvtinh { get; set; }
        public string nsx { get; set; }
        public System.DateTime hsd { get; set; }
        public int slnhap { get; set; }
        public int dongia { get; set; }
    
        public virtual PNHAP PNHAP { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
