//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPXUAT
    {
        public int sophieu { get; set; }
        public string mathuoc { get; set; }
        public string dvtinh { get; set; }
        public int slxuat { get; set; }
        public int dongia { get; set; }
    
        public virtual PXUAT PXUAT { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
