//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PXUAT
    {
        public int sophieu { get; set; }
        public string manv { get; set; }
        public System.DateTime ngayxuat { get; set; }
    
        public virtual CTPXUAT CTPXUAT { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
